name: Build Pear Desktop - Windows

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions: {}

env:
  NODE_VERSION: "24.x"

jobs:
  build-windows:
    name: Build Pear Desktop for Windows
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 11
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Windows application
        run: pnpm dist:win

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: pear-desktop-windows
          path: pack/*
          if-no-files-found: error
          retention-days: 7
